logging:
  root_log_level: INFO
  # When running in k8s, use JSON logger via env setting
  # formatter: json
  formatter: "standard"
  child_log_levels:
    mchpy: INFO
main:
  app_name: Flexpart-IFS-Preprocessor
  db_path: /src/db/sqlite3-db
  s3_buckets:
    input:
      endpoint_url: https://object-store.os-api.cci1.ecmwf.int
      name: flexpart-input
    output:
      endpoint_url: https://object-store.os-api.cci1.ecmwf.int
      name: flexprep-output
  time_settings:
    tincr: 1
    tstart: 0
